Add Python 3.9 to CI
equinor/libres pull request #1129
Opened 2021-03-18 16:49 UTC by dotfloat

2021-03-18 19:41 UTC, xjules approved these changes
LGTM!

2021-03-19 05:47 UTC, markusdregi commented on .github/workflows/python-bdist.yml
> -name: Python Binary Distribution
Why is this workflow going away?

2021-03-19 05:48 UTC, markusdregi requested changes
Please explain why the bdist-workflow disappears before merging. Besides that, Python 3.9 support is neat 😎

2021-03-19 08:08 UTC, dotfloat commented
It's a workflow that does nearly the same as `testing`. Except it doesn't run on PRs. So we have two workflows that eg. upload to PyPI. You'll notice that `master` fails CI most of the time. Most likely someone forgot to delete it.

2021-03-19 08:37 UTC, markusdregi commented
Thanks for the explanation @dotfloat! As the removal of the workflow is independent of introducing Python 3.9, can you please separate it into a separate commit? And in addition, rename the now `testing.yml` so that it becomes clear that is also does `distribution`? I applaud the cleaning of the workflow files though 👏🏻

2021-03-19 11:07 UTC, markusdregi approved these changes
📦

2021-03-19 11:07 UTC, merged