added careful copy job with corresponding test.
equinor/libres pull request #424
Opened 2018-11-06 14:44 UTC by ManInFez

**Task**
#416 

**Approach**
_Short description of the approach_

**Pre un-WIP checklist**
- [ ] Statoil tests pass locally
- [ ] Have completed graphical integration test steps

**Depends on**
* Statoil/libecl#

2018-11-06 14:45 UTC, abrautomate commented
Can one of the admins verify this patch?

2018-11-06 14:55 UTC, joakim-hove commented
Ok to test

2018-11-06 15:01 UTC, joakim-hove requested changes
Some minor changes - then she goes in. Good

2018-11-06 15:01 UTC, joakim-hove commented on python/res/fm/shell/shell.py
> +            raise IOError("Input argument:'%s' already exist" % target)
That the target file exists is perfectly OK - not exception.

2018-11-06 15:01 UTC, joakim-hove commented on python/res/fm/shell/shell.py
> +            raise IOError("Input argument:'%s' already exist" % target)
That the target file exists is perfectly OK - not exception.

2018-11-06 15:01 UTC, joakim-hove commented on share/ert/forward-models/shell/CAREFUL_COPY_FILE
> +STDERR      careful_copy_file.stderr
The std file descriptors are redirected by default - not necessary to do it explicitly.

2018-11-07 07:31 UTC, ManInFez commented on python/res/fm/shell/shell.py
> +            raise IOError("Input argument:'%s' already exist" % target)
Should the function fail silently? Would it not be a good idea to let the user know if the copy failed?

2018-11-07 07:38 UTC, joakim-hove commented on python/res/fm/shell/shell.py
> +            raise IOError("Input argument:'%s' already exist" % target)
Well - if the file is already present the copy should not proceed, and that is the expected operation of this function - i.e. *not* a failure. Could add a message like:
```
print("File: {} already present - not updated".format(target_file))
```

2018-11-07 07:39 UTC, ManInFez commented on python/res/fm/shell/shell.py
> +            raise IOError("Input argument:'%s' already exist" % target)
Very good, I will change it accordingly.

2018-11-07 08:28 UTC, joakim-hove approved these changes

2018-11-07 08:28 UTC, merged