Fix for collections ABC import DeprecationWarning
equinor/libres pull request #716
Opened 2019-10-08 10:37 UTC by wouterjdb

**Issue**
Resolves the DeprecationWarning that `collections` throws in stat.py

`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

**Approach**
Did as suggested by the warning, changed `from collections import Sequence` to `from collections.abc import Sequence`.

2019-10-08 10:39 UTC, ertomatic commented
Can one of the admins verify this patch?

2019-10-08 10:40 UTC, jokva commented
This won't work for python2. The correct way to do it is:

```
try:
    from collections.abc import Sequence
except ImportError:
    from collections import Sequence
```

The good part is that once py2 support is dropped, you can remove the try-except, and not change the actual import.

See: https://github.com/equinor/segyio/pull/414

2019-10-08 10:41 UTC, jokva requested changes
https://github.com/equinor/segyio/pull/414

2019-10-08 10:41 UTC, wouterjdb commented
Ok, hang on....

2019-10-08 10:42 UTC, wouterjdb commented
Now it is like you suggested:

```
try:
    from collections.abc import Sequence
except ImportError:
    from collections import Sequence
```

2019-10-08 12:23 UTC, jokva approved these changes

2019-10-08 12:23 UTC, jokva approved these changes

2019-10-09 12:55 UTC, markusdregi commented
Jenkins: Test this please

2019-10-09 13:10 UTC, markusdregi commented
@wouterjdb Could you please rebase this and squash your three commits into one ;)

2019-10-18 12:25 UTC, oyvindeide commented
Didn't hear from the author so I cherry-picked the PR into:
https://github.com/equinor/libres/pull/746
Closing this.

2019-10-18 12:25 UTC, closed without merging