Run rng_init on when running experiment
equinor/libres pull request #816
Opened 2019-11-25 14:48 UTC by ManInFez

Resolves equinor/scout#43

2019-11-25 17:06 UTC, joakim-hove commented
```C++
if (enkf_main->rng_manager)
    rng_manager_free(enkf_main->rng_manager);
```
and similar for the other argument.

2019-11-27 10:22 UTC, markusdregi commented on python/res/enkf/enkf_simulation_runner.py
> +        #self._enkf_main().initRun(run_context)
????

2019-11-27 10:40 UTC, ManInFez commented on python/res/enkf/enkf_simulation_runner.py
> +        #self._enkf_main().initRun(run_context)
whops.. pushed the removal to the wrong branch

2019-11-27 13:12 UTC, markusdregi commented
Can you please explain the idea behind the fix? In particular, I don't understand why you are removing the init call from the Python code...

Also, this is a code change without a test. Always scary! I get that this might be a bit difficult to test as of now, but could you please investigate the feasibility of testing and at the very least make an issue?

2019-11-27 13:45 UTC, ManInFez commented
The init call is already performed in create_runpath in the C-code. This is not an ideal fix, the execution flow should be taken care of properly. As far as I see it
- init_run must be called before create_runpath
- create_runpath must be called before "run pre-simulation workflow" 
- recreating the rng_manager after create_runpath will make things crash as some rng pointers are kept somewhere. 
- "run pre-simulation workflow" must happen before run simple step
 
Maybe we can discuss it tomorrow a bit?

2019-12-06 06:34 UTC, markusdregi requested changes
This currently breaks the workflows running the update step.

In addition, this is motivated as a feature in ERT/libres of reproducible parameters even when rerunning. We should make a test verifying that we get this behavior in the correct repo.

2019-12-19 13:42 UTC, ertomatic commented
Can one of the admins verify this patch?

2020-11-13 15:09 UTC, sondreso commented
This PR is closed due to inactivity. Feel free to rebase and adapt to the changes that have been introduced (mainly pip installable libres and black formatting), and reopen the PR :smile:

2020-11-13 15:09 UTC, closed without merging